### ISSUE TITLE
Declaring dependencies via a TOML table does not work

### ISSUE THREAD

**Issue by MLNW** [thunderstore-io/thunderstore-cli#69]
I'm trying to move to tcli to build and publish my package. The generated `thunderstore.toml` file when I run `tcli init` contains an inline table for declaring dependencies like this:

```toml
dependencies = { AuthorName-PackageName = "0.0.1" }
```

Inline tables do not allow new lines so declaring my dependent mods would result in a super long line which is horrible for version controlling:

```toml
dependencies = { Atopy-QuickPing = "1.5.3", Azumatt-AAA_Crafting = "1.0.5", Azumatt-AzuClock = "1.0.0", ComfyMods-ComfyQuickSlots = "1.0.9", denikson-BepInExPack_Valheim = "5.4.1901", Digitalroot-Digitalroots_Slope_Combat_Assistance = "2.0.2", Goldenrevolver-Quick_Stack_Store_Sort_Trash_Restock = "1.2.0", MathiasDecrock-Snap_Points_Made_Easy = "1.3.2", OdinPlus-OdinHorse = "1.1.0", OdinPlus-OdinsCraftyBoxes = "1.0.6", Smoothbrain-Farming = "2.1.3", Smoothbrain-Lumberjacking = "1.0.3", Smoothbrain-Mining = "1.1.3", Smoothbrain-Ranching = "1.1.1", Smoothbrain-Sailing = "1.1.4", thedefside-BetterUI_Reforged = "2.4.0" }
```

Making a proper table out of the inline table does not work though. AFAIK it should look like this:

```toml
[dependencies]
Atopy-QuickPing = "1.5.3"
Azumatt-AAA_Crafting = "1.0.5"
Azumatt-AzuClock = "1.0.0"
ComfyMods-ComfyQuickSlots = "1.0.9"
denikson-BepInExPack_Valheim = "5.4.1901"
Digitalroot-Digitalroots_Slope_Combat_Assistance = "2.0.2"
Goldenrevolver-Quick_Stack_Store_Sort_Trash_Restock = "1.2.0"
MathiasDecrock-Snap_Points_Made_Easy = "1.3.2"
OdinPlus-OdinHorse = "1.1.0"
OdinPlus-OdinsCraftyBoxes = "1.0.6"
Smoothbrain-Farming = "2.1.3"
Smoothbrain-Lumberjacking = "1.0.3"
Smoothbrain-Mining = "1.1.3"
Smoothbrain-Ranching = "1.1.1"
Smoothbrain-Sailing = "1.1.4"
thedefside-BetterUI_Reforged = "2.4.0"
```

But this results in a manifest file that looks like this:
![grafik](https://user-images.githubusercontent.com/20930814/210067096-9e147033-7689-4d66-9d0b-14efcf9fdcfb.png)

So either I'm doing something wrong or this functionality is bugged.
