### ISSUE TITLE
[Lethal Company] tcli publish category errors

### ISSUE THREAD

**Issue by KlutzyBubbles** [thunderstore-io/thunderstore-cli#99]
Trying to publish a mod with the categories `["mods", "serverside", "clientside", "tools"]` and the communities `["lethal-company"]` and getting the error

```
ERROR: Unexpected response from the server while publishing package:
Status code: 400 BadRequest
{"categories":{"1":["Object not found"],"2":["Object not found"]}}
Exiting
```

This happens on 0.2.1, 0.2.2 and 0.2.3. Not sure if i am just using the incorrect categories or if there is something that is going wrong. I tried looking through the code but i am unfamiliar with where i would find anything.

**Comment by Lordfirespeed** [comment]
You are using the incorrect categories, yes - 'object not found' is because that list can only contain 'global' categories, not community-specific ones, and `serverside` and `clientside` (indexes 1,2) are not global categories. 

You should do something like this:

```toml
[publish]
communities = ["foo", "bar"]

[publish.categories]
foo = ["mods", "foo-category-1", "foo-category-2"]
bar = ["mods", "bar-category-1", "bar-category-2"]
```
